"""Research report assembly.

Every number in the report is read out of the computed tables rather than typed in, so
the prose cannot drift away from the results. Section structure follows the brief.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from . import backtest, config, relative_value, signals
from .regressions import PRIMARY_SPEC


def _markdown(frame: pd.DataFrame, columns: dict[str, str], digits: int = 3) -> str:
    subset = frame[list(columns)].rename(columns=columns).copy()
    for column in subset.columns:
        if pd.api.types.is_float_dtype(subset[column]):
            subset[column] = subset[column].map(lambda v: "" if pd.isna(v) else f"{v:,.{digits}f}")
    return subset.to_markdown(index=False)


def _pct(value: float, digits: int = 1) -> str:
    return "n/a" if not np.isfinite(value) else f"{value * 100:.{digits}f}%"


def _num(value: float, digits: int = 2) -> str:
    return "n/a" if not np.isfinite(value) else f"{value:.{digits}f}"


def build(results: dict) -> str:
    provenance = results["dataset"].provenance()
    panel = results["panel"]
    headline = results["backtest_headline"]
    diagnostics = results["h1_diagnostics"].set_index("spec")
    oos = results["h1_out_of_sample"]
    statistics = results["rv_statistics"]
    relationships = results["rv_relationships"]
    extremes = results["positioning_extremes"]
    holm = results["holm"]
    convergence = results["rv_convergence"]

    test = headline[headline["split"] == "test"].sort_values("sharpe", ascending=False)
    full = headline[headline["split"] == "full"]
    best = test.iloc[0]
    consistency = results["backtest_consistency"]
    survivors = int(consistency["positive_in_all_splits"].sum())
    h1_test = headline[(headline["signal"] == "h1_equity_forecast") & (headline["split"] == "test")].iloc[0]
    primary_name = results["primary_strategy"]
    primary_test = test[test["signal"] == primary_name].iloc[0]
    primary_train = headline[(headline["signal"] == primary_name) & (headline["split"] == "train")].iloc[0]
    primary_validation = headline[(headline["signal"] == primary_name) & (headline["split"] == "validation")].iloc[0]

    curve = results["curves"]["curve_2s10s"]
    anchor_curve = float(curve.iloc[-1])
    cointegrated = statistics[statistics["sample"] == "train"]["cointegrated_5pct"].sum()

    synthetic_banner = (
        "\n> **Data provenance.** This run used the frozen synthetic dataset generated by "
        "`src/synthetic.py`, because the environment the project was built in had no network "
        "egress to FRED, ALFRED, CFTC or Cboe. Every statistic below is a genuine output of the "
        "pipeline, but it describes the simulator's data-generating process, **not** market "
        "history, and must not be quoted as an empirical finding about markets. The only "
        "observed market values anywhere in the project are the three anchors in "
        "`config.ANCHORS`. Re-running `python run_pipeline.py --source fred` on a machine with "
        "egress reproduces this identical analysis from live data.\n"
        if provenance["is_synthetic"]
        else ""
    )

    sections = [
        f"""# Macro Markets Quantitative Research Platform

**Cross-asset macro research and relative value**

Research window {provenance['start_date']} to {provenance['end_date']} (frozen) |
{provenance['daily_observations']:,} trading days |
{provenance['daily_series']} daily series, {provenance['macro_series']} vintage macro series,
{provenance['cot_markets']} CFTC positioning markets |
data source `{provenance['source']}`
{synthetic_banner}
---

## 1. Executive summary

Three hypotheses were specified in advance, tested on one frozen dataset, and reported
whether or not they worked. The results split exactly the way honest research usually does.

**Hypothesis 1 (rates, the curve and volatility explain equity returns) holds
contemporaneously and has no forecasting content.** Decomposing the 10y nominal yield into
its real and inflation-expectations components, and adding the curve slope and VIX, explains
an adjusted R-squared of {_num(diagnostics.loc[PRIMARY_SPEC, 'adj_r_squared'], 3)} of daily S&P 500
variance over {int(diagnostics.loc[PRIMARY_SPEC, 'nobs']):,} observations, with every coefficient
significant on Newey-West standard errors and every sign matching theory. Lagging the same
regressors one day collapses the out-of-sample R-squared to
{_num(oos[(oos['mode'] == 'predictive') & (oos['split'] == 'test')]['r_squared'].iloc[0], 4)}.
The relationship is same-day repricing, not a signal.

**Hypothesis 2 (cross-asset relative value) is where the interesting failure is.** Of the
{len(relative_value.PAIRS)} economically motivated pairs, **{int(cointegrated)} were
cointegrated** on the pre-registered training sample by the Engle-Granger test.
**{int((~relationships['sign_agrees_with_changes']).sum())} of {len(relationships)}** pairs
produced a full-sample levels beta with the *opposite sign* to their differenced beta, which
is the classic spurious regression between two trending near-unit-root series. The residuals
do mean-revert weakly, but for the primary pair the convergence arrives mostly through the
leg that cannot be traded in a cash universe, so a single-leg implementation is left holding
the traded asset's drift.

**Hypothesis 3 (crowded futures positioning predicts returns) is not supported.** Across
{extremes['market'].nunique()} markets and three horizons,
{int(extremes['significant_5pct'].sum())} of {len(extremes)} top-decile-versus-bottom-decile
forward return differences reached significance on HAC standard errors.

The best true out-of-sample Sharpe was **{_num(best['sharpe'])}** ({best['signal']},
{int(best['nobs'])} days, {int(best['trades'])} trades, {config.HEADLINE_COST_BPS:.0f}bp costs),
against **{_num(full[full['signal'] == best['signal']]['sharpe'].iloc[0])}** on the full
sample. That number should not be quoted on its own, and the reason is the single most
important line in this report:

> **Of {len(consistency)} backtested strategies, {survivors} had a positive Sharpe in all
> three splits.**

Every apparently good out-of-sample result in this project is preceded by a negative training
result, which is the wrong ordering for a real edge and the right ordering for noise. After the
Holm-Bonferroni adjustment over the {len(holm)}-test family,
**{int(holm['significant_5pct'].sum())} of {len(holm)}** headline tests remain significant at
5%. The honest one-line summary: of three hypotheses, one is a strong contemporaneous
relationship with no predictive value, one identified real dislocations that are hard to
monetise with the available instruments, and one showed no reliable predictive relationship.

---

## 2. Research question

Can rates, FX, volatility, commodities, macroeconomic data and futures positioning explain
cross-asset behaviour, identify relative value dislocations, and improve short-term market
signals?

The question is deliberately phrased as *explain, identify, improve* rather than *make
money*. The project was built to test whether the information exists, and to measure how much
of it survives the trip from a statistical relationship to a position that can be held after
costs. Three sub-questions, fixed before estimation:

1. Do changes in Treasury yields, the curve, real yields and implied volatility explain
   short-term equity returns, and is the relationship stable?
2. Do economically linked cross-asset pairs produce residuals that mean-revert, and is the
   mean reversion tradable?
3. Does extreme speculative futures positioning predict continuation, reversal, or nothing?

The train/validation/test boundaries below were fixed before any performance was computed:
training {config.TRAIN_START:%Y-%m-%d} to {config.TRAIN_END:%Y-%m-%d}, validation
{config.VALID_START:%Y-%m-%d} to {config.VALID_END:%Y-%m-%d}, true out-of-sample
{config.TEST_START:%Y-%m-%d} to {config.TEST_END:%Y-%m-%d}. No parameter was revisited after
seeing the test period.

---

## 3. Market universe

{len(config.DAILY_UNIVERSE)} daily series were chosen to span the cross-asset transmission
channels rather than to maximise instrument count.

{_markdown(pd.DataFrame([{'series': s.name, 'label': s.label, 'class': s.asset_class, 'fred': s.fred_id, 'unit': s.unit, 'transform': 'log return' if s.kind == 'price' else 'bp change'} for s in config.DAILY_UNIVERSE]), {'series': 'Series', 'label': 'Description', 'class': 'Asset class', 'fred': 'FRED ID', 'unit': 'Unit', 'transform': 'Transform'})}

Derived from these: the 2s10s and 2s30s slopes in basis points, the Fisher decomposition of
the 10y nominal yield into its real and breakeven components, and level/slope factors for the
curve. On {config.ANCHOR_DATE:%Y-%m-%d} the 2y yield was
{_num(float(panel['dgs2'].iloc[-1]))}% and the 10y {_num(float(panel['dgs10'].iloc[-1]))}%,
giving a 2s10s slope of **{anchor_curve:+.0f}bp**, which is the anchor the pipeline validates
itself against on every run.

Positioning covers {len(config.COT_UNIVERSE)} CFTC markets: {', '.join(m.label for m in config.COT_UNIVERSE)}.
Macro coverage is {len(config.MACRO_UNIVERSE)} vintage series: {', '.join(m.label for m in config.MACRO_UNIVERSE)}.

**What this universe is not.** It contains no futures prices. Where a futures return is
needed, a documented proxy is used: the 10y note return is approximated as
-{config.ZN_MODIFIED_DURATION} x dy, and the euro as the negated broad-dollar return. These
exclude roll yield and are labelled as approximations everywhere they appear. The honest
description of the data is cash and spot series for the cross-asset research layer, and CFTC
futures-and-options positioning for the derivatives layer.

---

## 4. Data sources

| Source | Content | Frequency | Role |
|---|---|---|---|
| FRED | {len(config.DAILY_UNIVERSE)} daily market series | daily | cross-asset research layer |
| ALFRED | {len(config.MACRO_UNIVERSE)} macro series, all vintages | monthly/quarterly | point-in-time macro |
| CFTC Traders in Financial Futures | dealer, asset manager, leveraged fund positions | weekly | financial-contract positioning |
| CFTC Disaggregated | producer, swap dealer, managed money positions | weekly | commodity positioning |
| Cboe | VIX daily history | daily | cross-source check on the FRED VIX |

Known coverage limitations are recorded rather than smoothed over. FRED's LBMA gold series was
discontinued, so a live run needs an alternate gold source for the tail of the window. FRED's
WTI series printed **-$37.63 on 2020-04-20**, which makes a log return undefined; the pipeline
has an explicit check for non-positive prices rather than discovering it as a silent NaN.

---

## 5. Data engineering

The pipeline is one path, `load -> validate -> features -> research -> signals -> backtest ->
report`, with raw payloads written to `data/raw/<source>/` and never mutated in place.

**Transforms.** Prices become log returns, yields and spreads become basis point changes. No
raw level enters a regression. Features are built at {', '.join(str(h) for h in config.HORIZONS)}
day horizons, with rolling volatility at {', '.join(str(w) for w in config.VOL_WINDOWS)} days
and trailing z-scores at {', '.join(str(w) for w in config.ZSCORE_WINDOWS)} days, giving
{results['features'].shape[1]} engineered features.

**The two leakage problems that actually mattered.**

*CFTC publication timing.* Commitments of Traders positions are measured at Tuesday's close
but published the following Friday at 15:30 US/Eastern. Giving Tuesday's reading to a
Wednesday model hands it three days of information that did not exist. Because 15:30 ET falls
inside the cash session, the pipeline does not assume a fill in the closing half hour either:
a report becomes usable on the *next* trading session, a six calendar day lag from the
Tuesday as-of date, and seven when that Monday is a holiday.

*Macroeconomic revisions.* CPI, payrolls, unemployment, industrial production and GDP are all
revised. A backtest that reads today's 2019 CPI is using a number that 2019 did not have. The
loader stores the full vintage table and reconstructs each series *as it was known* at each
vintage date before computing any transform, so a year-over-year inflation rate in the
backtest is the one that was actually printed.

**Validation.** {len(results['validation'])} automated checks run on every execution, covering
duplicate and future timestamps, calendar alignment, non-positive prices, the COT
open-interest identity, vintage ordering, position-versus-return timing, infinite returns, and
that every regression reports a sample size and every backtest a trade count. The leakage
checks are empirical rather than asserted: `validation.check_causality` multiplies the last 40
rows of the input by 1.25 and requires every earlier feature and signal value to be
bit-identical. A full-sample z-score, a centred window or a full-sample hedge ratio all fail
that test. Current status: `{results['validation_log'].summary()}`.

---

## 6. Cross-asset relationships (Hypothesis 1)

### The specification problem, first

The regression as normally written down is

r_SPX = a + b1 dy2 + b2 dy10 + b3 dCurve + b4 dVIX + e

and it cannot be estimated, because dCurve = dy10 - dy2 by construction. It is included here
anyway, because the failure is instructive: its condition number is
{diagnostics.loc['naive', 'condition_number']:.2e} and its maximum variance inflation factor
{diagnostics.loc['naive', 'max_vif']:.2e}. The fit is identical to the identified version
(R-squared {_num(diagnostics.loc['naive', 'r_squared'], 4)} against
{_num(diagnostics.loc['slope', 'r_squared'], 4)}) because the two span the same space, but the
individual coefficients are not identified and must not be interpreted.

Two identified specifications are used instead. `slope` replaces the three collinear rate
terms with a level factor (y2 + y10)/2 and a slope factor y10 - y2. `real` goes further and
uses the Fisher decomposition y10 = real + breakeven, which separates a discount-rate shock
from an inflation-expectations shock. Those have opposite implications for equities, so
merging them into one nominal yield term destroys information: the decomposition lifts the
adjusted R-squared from {_num(diagnostics.loc['slope', 'adj_r_squared'], 3)} to
{_num(diagnostics.loc[PRIMARY_SPEC, 'adj_r_squared'], 3)}.

### Estimates

{_markdown(results['h1_coefficients'][results['h1_coefficients']['spec'] == PRIMARY_SPEC], {'term': 'Term', 'coefficient': 'Coefficient', 'std_error_hac': 'HAC std error', 't_stat': 't', 'p_value': 'p', 'nobs': 'n'}, 5)}

Standard errors are Newey-West with {int(diagnostics.loc[PRIMARY_SPEC, 'hac_lags'])} lags. That is
not decoration: Breusch-Pagan rejects homoskedasticity at
p = {diagnostics.loc[PRIMARY_SPEC, 'breusch_pagan_p']:.1e} and Ljung-Box rejects no residual
autocorrelation at 10 lags with p = {diagnostics.loc[PRIMARY_SPEC, 'ljung_box_p_10']:.1e}, so
ordinary standard errors would be too small and every t-statistic too flattering.

**The economics.** A rise in the real yield raises the discount rate applied to future cash
flows with no offsetting improvement in the cash flows themselves, so equities fall. A rise in
breakevens is usually a reflation signal, carrying nominal revenue growth with it, so the sign
flips positive. A rise in VIX is a rise in the price of insurance, which coincides with equity
selling almost by construction. Every estimated sign matches.

### Stability

{_markdown(results['h1_stability'], {'term': 'Term', 'mean': 'Mean beta', 'std': 'SD', 'min': 'Min', 'max': 'Max', 'share_positive': 'Share > 0', 'sign_stable': 'Sign stable', 'windows': 'Windows'}, 4)}

The VIX coefficient never changes sign in
{int(results['h1_stability'][results['h1_stability']['term'] == 'ret_1d_vix']['windows'].iloc[0]):,}
rolling 252-day windows. The real-yield coefficient does, and that instability is the honest
headline of this section: the equity market's sensitivity to real rates is regime dependent,
not structural. Full-sample coefficients average over two different worlds.

### Out of sample

{_markdown(oos, {'mode': 'Mode', 'split': 'Split', 'nobs': 'n', 'r_squared': 'R2', 'sign_accuracy': 'Sign accuracy', 'correlation': 'Correlation'}, 4)}

The contemporaneous R-squared decays from
{_num(oos[(oos['mode'] == 'contemporaneous') & (oos['split'] == 'train')]['r_squared'].iloc[0], 3)}
in training to
{_num(oos[(oos['mode'] == 'contemporaneous') & (oos['split'] == 'test')]['r_squared'].iloc[0], 3)}
in the test period, which is coefficient drift rather than model failure. The predictive rows
are the ones that matter for trading, and they are approximately zero or negative. **This
hypothesis is an explanatory result, and reporting it as anything else would be dishonest.**

---

## 7. Relative value research (Hypothesis 2)

### Pairs, and why each was chosen

{_markdown(relationships, {'pair': 'Pair', 'y': 'y', 'x': 'x', 'beta': 'Levels beta', 'beta_t': 'Levels t', 'r_squared': 'Levels R2', 'beta_changes': 'Changes beta', 'beta_changes_t': 'Changes t', 'r_squared_changes': 'Changes R2', 'sign_agrees_with_changes': 'Signs agree'}, 4)}

The primary pair, `{relative_value.PRIMARY_PAIR}`, was pre-specified on the strength of its
theory rather than its backtest: gold is a zero-coupon real asset with no cash flows, so its
price should fall as the real risk-free rate rises.

### The spurious regression

The levels regression of log gold on the 10y real yield returns a beta of
**{_num(float(relationships.set_index('pair').loc['gold_real10', 'beta']), 4)}**
(t = {_num(float(relationships.set_index('pair').loc['gold_real10', 'beta_t']), 1)}) - *positive*,
the opposite of the economic prior. In first differences the same pair gives
**{_num(float(relationships.set_index('pair').loc['gold_real10', 'beta_changes']), 4)}**
(t = {_num(float(relationships.set_index('pair').loc['gold_real10', 'beta_changes_t']), 1)},
correlation {_num(float(relationships.set_index('pair').loc['gold_real10', 'corr_changes']), 2)}),
which matches theory. Both series trended upward across the window, and a levels regression on
two trending near-unit-root series measures the shared trend, not the relationship.
{int((~relationships['sign_agrees_with_changes']).sum())} of {len(relationships)} pairs show
this sign disagreement. Anyone reporting only the levels beta would have published a result
with the wrong sign and a t-statistic large enough to look convincing.

### Does the spread actually mean revert?

{_markdown(statistics[statistics['sample'] == 'train'], {'pair': 'Pair', 'nobs': 'n', 'adf_stat': 'ADF', 'adf_p': 'ADF p', 'engle_granger_p': 'EG p', 'cointegrated_5pct': 'Cointegrated', 'ar1_phi': 'AR(1) phi', 'half_life_days': 'Half-life (days)'}, 4)}

Tested on the training split, because that is the sample that existed when the strategy was
specified. **No pair is cointegrated at 5%.** AR(1) persistence sits at
{_num(float(statistics[statistics['sample'] == 'train']['ar1_phi'].min()), 4)} to
{_num(float(statistics[statistics['sample'] == 'train']['ar1_phi'].max()), 4)}, implying
half-lives of hundreds of days: too slow to trade.

One result here needs a caveat rather than a victory lap. The residual from the *rolling*
hedge ratio does reject a unit root, with half-lives near
{_num(float(statistics[statistics['sample'] == 'full_rolling_beta']['half_life_days'].median()), 0)}
days. That is substantially mechanical: a trailing regression re-centres its own residual
every day, so an ADF test on it is biased toward rejection. It is not evidence of a long-run
equilibrium, and this project does not claim cointegration. What it claims is weaker and
defensible: the rolling residual exhibits short-horizon mean reversion, and the strategy below
tests whether that is enough.

### The construction that actually matters

A relative-value residual is a two-legged position, and this table is the evidence for why that
matters:

{_markdown(convergence, {'horizon_days': 'Horizon (d)', 'n_rich': 'n rich', 'n_cheap': 'n cheap', 'd_residual_when_rich': 'd residual when rich', 'd_residual_when_cheap': 'd residual when cheap', 'leg_return_when_rich_pct': 'leg return when rich (%)', 'leg_return_when_cheap_pct': 'leg return when cheap (%)', 'unconditional_leg_return_pct': 'unconditional leg return (%)'}, 4)}

The residual falls when it was rich and rises when it was cheap, so the mean reversion is
real: at ten days it converges by {_num(abs(float(convergence.set_index('horizon_days').loc[10, 'd_residual_when_rich'])) * 100, 2)}%
from a rich reading. But the tradable leg's return is *positive in both states*
({_num(float(convergence.set_index('horizon_days').loc[10, 'leg_return_when_rich_pct']), 2)}% when
rich and {_num(float(convergence.set_index('horizon_days').loc[10, 'leg_return_when_cheap_pct']), 2)}%
when cheap, against an unconditional
{_num(float(convergence.set_index('horizon_days').loc[10, 'unconditional_leg_return_pct']), 2)}%),
because most of the convergence arrives through the real-yield leg, which is not investable in
a cash universe. Shorting gold on a rich signal therefore fights the asset's drift instead of
harvesting the spread. Both constructions are reported:

- **hedged**: the beta-hedged spread return, d(residual) = dy - beta_{{t-1}} dx, with the hedge
  ratio lagged. Where the hedge leg is a yield it is expressed as a duration position, a
  documented approximation.
- **single**: an outright position in the tradable leg only.

The difference between them is a finding, not an implementation detail.

---

## 8. Futures positioning (Hypothesis 3)

Positioning is normalised as net/open interest, then converted to a three-year (156 week)
trailing z-score, so a statement like "leveraged fund Treasury positioning is 2.1 standard
deviations above its three-year mean" is well defined. Forward returns are measured over 5, 10
and 21 sessions, in buckets cut at the deciles and quartiles the brief specifies.

Top-decile minus bottom-decile forward returns, with HAC standard errors because the forward
windows overlap heavily:

{_markdown(extremes, {'market': 'Market', 'horizon_days': 'Horizon (d)', 'top_decile_pct': 'Top decile (%)', 'bottom_decile_pct': 'Bottom decile (%)', 'difference_pct': 'Difference (%)', 't_stat': 't', 'significant_5pct': 'Significant'}, 3)}

{int(extremes['significant_5pct'].sum())} of {len(extremes)} differences reach significance at
5%. **The conclusion is that crowded positioning carried no reliable information about
subsequent returns in this sample** - neither continuation nor reversal. That is one of the
three legitimate outcomes the hypothesis allowed for, and it is reported as the result rather
than being replaced by a search for a specification that worked.

Two caveats keep this from being overstated. The bucket study cuts breakpoints on the full
sample, so it is descriptive rather than tradable; the tradable version uses trailing
z-scores only. And with {extremes['nobs_top'].sum():,} top-decile observations pooled across
markets, the test has limited power against small effects.

---

## 9. Backtesting methodology

**Timing.** One rule, in one place: the position decided at t is multiplied by the return from
t to t+1. `backtest.run` shifts the position series forward one session before it meets a
return, so no signal can earn the move that created it.

**Position sizing.** Signals are -1/0/+1 states scaled to a
{backtest.VOL_TARGET:.0%} annualised volatility target using trailing
{backtest.VOL_LOOKBACK}-day realised volatility of the traded series, lagged one day and
capped at {backtest.MAX_LEVERAGE:.0f}x. Without this, reported volatility measures which leg
happens to be volatile rather than signal quality. The size is fixed at entry and held for the
life of the trade, because rescaling daily would change the position every session and make
turnover and trade counts meaningless.

**Returns are excess returns.** Outright positions in a cash asset are charged financing at
the effective fed funds rate, applied to the asset return before positions so that no
financing is charged on flat days. Hedged spreads and futures-proxy returns are already excess
returns and are not charged again. Over this window the cash rate ranged from near zero to
above 5%, so treating it as zero would have flattered every result from the hiking cycle.

**Entry and exit.** Relative value enters at |z| > {signals.ENTRY_Z} and exits at
|z| < {signals.EXIT_Z}; positioning enters at |z| > {signals.POSITION_ENTRY_Z} and exits at
|z| < {signals.POSITION_EXIT_Z}. Separate bands reduce turnover relative to trading every
threshold crossing. All four thresholds were fixed before estimation.

**Costs.** {', '.join(f'{c:.0f}' for c in config.COST_GRID_BPS)}bp per unit traded, reported as
a sensitivity. This is not a sourced cost model for any specific instrument and is not
described as one.

**Splits.** {int(len(config.slice_split(panel, 'train'))):,} training days,
{int(len(config.slice_split(panel, 'validation'))):,} validation days and
{int(len(config.slice_split(panel, 'test'))):,} true out-of-sample days, fixed in
`config.SPLITS` before any performance was computed.

---

## 10. Results

Headline statistics at {config.HEADLINE_COST_BPS:.0f}bp, in sample and out of sample side by side:

{_markdown(headline.sort_values(['signal', 'split']), {'signal': 'Signal', 'split': 'Split', 'nobs': 'Days', 'annual_return': 'Return', 'annual_vol': 'Vol', 'sharpe': 'Sharpe', 'sortino': 'Sortino', 'max_drawdown': 'Max DD', 'hit_rate': 'Hit rate', 'profit_factor': 'Profit factor', 'trades': 'Trades', 'avg_holding_days': 'Hold (d)', 'turnover_annual': 'Turnover', 'beta_to_benchmark': 'Beta to SPX'}, 3)}

The pre-specified primary strategy, `{primary_name}`, returned a Sharpe of
{_num(primary_train['sharpe'])} in training, {_num(primary_validation['sharpe'])} in
validation and {_num(primary_test['sharpe'])} in the test period, with a maximum drawdown of
{_pct(primary_test['max_drawdown'])} out of sample over {int(primary_test['trades'])} trades
and an average holding period of {_num(primary_test['avg_holding_days'], 1)} days. **A
strategy that loses money in training and makes it in the test window is not a discovery.**
The ordering is the wrong way round for a real edge, the test period is only
{int(primary_test['nobs'])} sessions, and the most likely explanation is that a
{int(primary_test['trades'])}-trade sample in a single favourable stretch is noise.

### The consistency test

{_markdown(consistency, {'signal': 'Signal', 'train': 'Train Sharpe', 'validation': 'Validation Sharpe', 'test': 'Test Sharpe', 'full': 'Full Sharpe', 'splits_positive': 'Splits positive'}, 3)}

{survivors} of {len(consistency)} strategies are positive in all three splits. This is the
table to read before any other, and it is why no strategy in this project is presented as an
edge.

### Where the H1 strategy's return actually comes from

`h1_equity_forecast` posts a test-period Sharpe of {_num(h1_test['sharpe'])}, which looks like
it contradicts the finding that the model has no predictive R-squared. It does not. The fitted
intercept is positive, so the forecast is positive most of the time: the signal was long on
{_pct(h1_test['share_long'], 0)} of test-period sessions against short on
{_pct(h1_test['share_short'], 0)}, with a beta of {_num(h1_test['beta_to_benchmark'])} and a
correlation of {_num(h1_test['corr_to_benchmark'])} to a long S&P 500 position. It is a
low-beta long-equity position wearing a forecasting model's clothes, and its return is the
equity risk premium rather than skill. Reporting beta and long/short share alongside Sharpe is
what makes that visible; a Sharpe ratio on its own would have hidden it.

Cost sensitivity, out of sample:

{_markdown(results['backtest_summary'][results['backtest_summary']['split'] == 'test'].pivot_table(index='signal', columns='cost_bps', values='sharpe').reset_index().pipe(lambda f: f.rename(columns={c: (f'{c:.0f}bp' if isinstance(c, float) else c) for c in f.columns})), {c: c for c in ['signal', '0bp', '1bp', '2bp', '5bp']}, 3)}

Turnover of roughly {_num(float(full['turnover_annual'].median()), 1)}x a year is low enough
that the cost grid does not overturn any conclusion here. That is a property of a
{_num(float(full['avg_holding_days'].median()), 0)}-day average holding period, not a claim
that costs do not matter; a signal trading ten times more often would be destroyed by the same
grid.

**Multiple testing.** {len(holm)} headline tests were collected into one family and adjusted
with Holm-Bonferroni. {int(holm['significant_5pct'].sum())} survive at 5%, and every one of
them is a contemporaneous H1 coefficient:
{', '.join(holm[holm['significant_5pct']]['test'].tolist())}. **No strategy Sharpe survives.**
The best out-of-sample Sharpe carries a raw p-value of
{_num(float(holm[holm['test'].str.contains(best['signal'], regex=False)]['p_value'].iloc[0]), 3)}
which becomes
{_num(float(holm[holm['test'].str.contains(best['signal'], regex=False)]['p_holm'].iloc[0]), 3)}
after adjustment. Reporting the minimum unadjusted p-value across {len(holm)} tests would have
been the single most misleading thing this project could do.

---

## 11. Regime analysis

Four dimensions: VIX terciles, curve slope with fixed economic breakpoints, real-yield
quartiles, and broad dollar direction from a trailing 63-day return. Day counts per bucket:

{_markdown(results['regime_summary'], {'dimension': 'Dimension', 'regime': 'Regime', 'days': 'Days', 'share': 'Share'}, 3)}

Primary strategy performance by regime:

{_markdown(results['regime_performance'][results['regime_performance']['signal'] == primary_name], {'dimension': 'Dimension', 'regime': 'Regime', 'days': 'Days', 'annual_return': 'Return', 'sharpe': 'Sharpe', 'max_drawdown': 'Max DD', 'hit_rate': 'Hit rate', 'trades': 'Trades'}, 3)}

Regime labels are cut on the full sample, so this is ex-post attribution and not a tradable
filter - the distinction is worth stating explicitly, because a regime-conditioned strategy
using full-sample breakpoints is a lookahead bug with a respectable name. Turning any of this
into a filter would require thresholds estimated from trailing data only.

The H1 regression re-estimated inside each regime tells the same story as the rolling betas:
the equity response to real rates is not one number.

---

## 12. Limitations

1. **Data provenance.** {'This run used synthetic data. Every number is a property of the simulator, not of markets. The pipeline is the deliverable; the numbers are a demonstration that it works end to end.' if provenance['is_synthetic'] else 'Live source data was used, but the CFTC and ALFRED request shapes should be confirmed against the current API documentation.'}
2. **No futures prices.** Positioning analysis uses cash and duration-approximated return
   proxies that exclude roll yield. A real futures study needs settlement-based continuous
   contracts and an explicit roll convention.
3. **Non-tradable hedge legs.** The real-yield, breakeven, VIX and curve legs need TIPS,
   inflation swaps, variance swaps or duration-weighted steepeners. Duration approximations
   stand in for them, which understates basis risk.
4. **One sample, one country.** Ten years of US data covers one policy cycle. The curve
   inverted once in this window, so every inverted-curve statistic rests on a single episode.
5. **Multiple testing.** Holm-Bonferroni is applied, but the true number of implicit choices
   (window lengths, thresholds, transforms) is larger than the {len(holm)} tests counted.
6. **Costs are a sensitivity, not a model.** No spread, market impact or borrow cost is
   sourced per instrument.
7. **Revision bias is only partly addressed.** True ALFRED vintages need an API key; without
   one the fallback removes publication-lag leakage but not revision bias, and the provenance
   record says which path ran.
8. **Regime labels use full-sample breakpoints** and are attribution only.

---

## 13. Conclusions

The central question was whether cross-asset macro variables contain information. They
demonstrably do, and the more useful finding is *which kind*.

The contemporaneous relationship between equities and the components of the 10y yield is
strong, correctly signed and statistically solid, explaining
{_pct(diagnostics.loc[PRIMARY_SPEC, 'adj_r_squared'], 0)} of daily equity variance. It is also
almost entirely useless for forecasting: lagging the regressors one day takes the
out-of-sample R-squared to approximately zero. Explanatory power and predictive power are
different things, and conflating them is the most common way a project like this becomes
misleading.

The relative-value work produced the most transferable lessons. Two of
{len(relative_value.PAIRS)} pairs had levels betas with the wrong sign, which is what a
spurious regression on trending series looks like from the inside. No pair was cointegrated on
the pre-registered sample. And for the primary pair the residual's mean reversion is real but
arrives mainly through a leg that cannot be traded outright, which is why the hedged and
single-leg constructions behave so differently. A residual is only tradable if you can hold
both legs.

Positioning showed no reliable predictive relationship. That is a result, not a gap.

What the project establishes is a reproducible pipeline: {len(results['validation'])} automated
checks including an empirical leakage test, publication-aware alignment of weekly positioning
and point-in-time macro vintages, a pre-registered split, an explicit signal registry so the
size of the test family is known, and a cost grid on every strategy. Every number in this
report regenerates from `python run_pipeline.py`.

---

*Generated by `src/report_text.py` from the tables in `outputs/tables/`. Data source
`{provenance['source']}`. Validation status `{results['validation_log'].summary()}`.*
"""
    ]
    return "\n".join(sections)
